import React, { useState, useEffect, useContext } from "react";
import { Button, Form, Input, Select, message } from "antd";
// import { InboxOutlined, UploadOutlined } from "@ant-design/icons";
// import type { FormInstance } from "antd/es/form";

// amplify API
import { Storage, API, graphqlOperation } from "aws-amplify";
// import * as mutations from "../../../graphql/mutations";
import { MenuContext } from "../../../contexts/MenuContext";
import { v4 as uuidv4 } from "uuid";
import config from "../../../aws-exports";

import { useAuthContext } from "../../../contexts/AuthContext";
import { useGerenteContext } from "../../../contexts/GerenteContext";
import GROUPS from "../../../constants/groups";
import { listOPTICAS } from "../../../graphql/queries";
import LaboratorioSelector from "../../RoleBased/LaboratorioSelector";
import { createINVENTARIO } from "../../../graphql/mutations";
const {
  aws_user_files_s3_bucket_region: region,
  aws_user_files_s3_bucket: bucket,
} = config;

const { Option } = Select;

function CrearInventario() {
  // usesate url y key
  const { groupName } = useAuthContext();

  const { cambiarComponent } = useContext(MenuContext);
  const [nombreProducto, setNombreProducto] = useState("");
  const [categoria, setCategoria] = useState("");
  const [proveedor, setProveedor] = useState("");
  const [costo, setCosto] = useState(0);
  const [precioVenta, setPrecioVenta] = useState(0);
  const [color, setColor] = useState("");
  const [stock, setStock] = useState(0);
  const [tipoEstructura, setTipoEstructura] = useState("");
  const [urlImagen, setUrlImagen] = useState("");
  const [tipoMaterial, setTipoMaterial] = useState("");
  const [opticaID, setOpticaID] = useState("");
  const [opticas, setOpticas] = useState([]);

  // optica id
  const { labId } = useGerenteContext();

  useEffect(() => {
    const searchOpticas = async () => {
      if (groupName !== GROUPS.SUPER_ADMIN) {
        setOpticaID(labId);
      } else {
        try {
          const result = await API.graphql(graphqlOperation(listOPTICAS));
          setOpticas(result.data.listOPTICAS.items);
        } catch (error) {
          console.log(error);
        }
      }
    };
    searchOpticas();
  }, [groupName, labId]);
  const dataExcel = [
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "XF VISION",
      tipoEstructura: "TR90 7369",
      color: "AZUL/CAFE",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "4",
      costo: "45",
      precioVenta: "300",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "XF VISION",
      tipoEstructura: "TR90 7396",
      color: "AZL/CFE/GRIS",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "3",
      costo: "45",
      precioVenta: "300",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "RIOTO",
      tipoEstructura: "R6588",
      color: "CAFE/NEGRO/DOR",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "1",
      costo: "60",
      precioVenta: "300",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "RIOTO",
      tipoEstructura: "R6581",
      color: "NGRO/DOR/AZUL",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "1",
      costo: "60",
      precioVenta: "300",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "DOTTI",
      tipoEstructura: "3012",
      color: "AZUL",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "1",
      costo: "45",
      precioVenta: "300",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "CLUB ROMA",
      tipoEstructura: "604",
      color: "AZUL/NEGRO",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "2",
      costo: "48",
      precioVenta: "300",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "PARIS T.",
      tipoEstructura: "23",
      color: "NEGRO",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "1",
      costo: "32",
      precioVenta: "200",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "BLACK",
      tipoEstructura: "2013",
      color: "AZUL TURQUESA",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "0",
      costo: "75",
      precioVenta: "300",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "BLACK",
      tipoEstructura: "2002",
      color: "NEGRO",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "0",
      costo: "75",
      precioVenta: "300",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "ROSELO",
      tipoEstructura: "ROS-0752",
      color: "NEGRO",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "0",
      costo: "100",
      precioVenta: "300",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "PINKY",
      tipoEstructura: "SE-007",
      color: "NEGRO/DORADO",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "1",
      costo: "195",
      precioVenta: "600",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "LA VITA",
      tipoEstructura: "6309",
      color: "AZUL",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "1",
      costo: "60",
      precioVenta: "300",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "LA VITA",
      tipoEstructura: "6359",
      color: "AZUL TURQUESA",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "3",
      costo: "60",
      precioVenta: "300",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "PRETTY",
      tipoEstructura: "3788",
      color: "ROSA/DORADO",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "0",
      costo: "105",
      precioVenta: "500",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "PRETTY",
      tipoEstructura: "PG-21004",
      color: "ROJO/DORADO",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "1",
      costo: "105",
      precioVenta: "500",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "PRETTY",
      tipoEstructura: "M-7135",
      color: "AZUL/GRIS",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "0",
      costo: "105",
      precioVenta: "500",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "PRETTY",
      tipoEstructura: "GK-7324",
      color: "NEGRO/DORADO",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "2",
      costo: "105",
      precioVenta: "500",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "PRETTY",
      tipoEstructura: "M-7137",
      color: "NEGRO/DORADO",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "3",
      costo: "105",
      precioVenta: "500",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "PRETTY",
      tipoEstructura: "7020",
      color: "NEGRO/DORADO",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "1",
      costo: "105",
      precioVenta: "500",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "PRETTY",
      tipoEstructura: "AM-3052",
      color: "AZUL/PLATEADO",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "0",
      costo: "105",
      precioVenta: "500",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "PRETTY",
      tipoEstructura: "PG-3013",
      color: "AZUL/DORADO",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "2",
      costo: "100",
      precioVenta: "500",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "PRETTY",
      tipoEstructura: "AM-3006",
      color: "VERDE/DORADO",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "0",
      costo: "105",
      precioVenta: "500",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "PRETTY",
      tipoEstructura: "PG-3017",
      color: "DORADO/CAFE",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "1",
      costo: "105",
      precioVenta: "500",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "PRETTY",
      tipoEstructura: "7125",
      color: "ROSA/DORADO",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "1",
      costo: "105",
      precioVenta: "500",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "INDIGO",
      tipoEstructura: "7825",
      color: "NEGRO",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "0",
      costo: "170",
      precioVenta: "500",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "MAXIMUN",
      tipoEstructura: "7189",
      color: "DORADO/CAFE",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "2",
      costo: "100",
      precioVenta: "500",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "MAXIMUN",
      tipoEstructura: "7178",
      color: "NEGRO",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "1",
      costo: "105",
      precioVenta: "500",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "MAXIMUN",
      tipoEstructura: "7186",
      color: "DORADO/CAFE",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "1",
      costo: "105",
      precioVenta: "500",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "MAXIMUN",
      tipoEstructura: "7226",
      color: "NEGRO/DORADO",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "3",
      costo: "105",
      precioVenta: "500",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "MAXIMUN",
      tipoEstructura: "7177",
      color: "NEGRO",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "2",
      costo: "105",
      precioVenta: "500",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "MAXIMUN",
      tipoEstructura: "7198",
      color: "CAFE/PLATEADO",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "0",
      costo: "105",
      precioVenta: "500",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "MAXIMUN",
      tipoEstructura: "7157",
      color: "NEGRO",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "4",
      costo: "105",
      precioVenta: "500",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "JAY JAYS",
      tipoEstructura: "JAY-123",
      color: "ROSA/AZUL",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "5",
      costo: "45",
      precioVenta: "350",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "JAY JAYS",
      tipoEstructura: "JAY-115",
      color: "CAFE/NEGRO",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "1",
      costo: "45",
      precioVenta: "350",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "JAY JAYS",
      tipoEstructura: "JAY-1002",
      color: "NEGRO/AZUL",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "0",
      costo: "45",
      precioVenta: "350",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "C MARK",
      tipoEstructura: "CM-M222P",
      color: "GRIS/TRANS.",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "0",
      costo: "50",
      precioVenta: "350",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "C MARCK",
      tipoEstructura: "J2012P",
      color: "GRIS/VER/NEGRO",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "5",
      costo: "60",
      precioVenta: "350",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "C MARK KIDS",
      tipoEstructura: "1999",
      color: "AZUL Y ROSA",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "2",
      costo: "315",
      precioVenta: "800",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "C MARK",
      tipoEstructura: "CMJO-7005",
      color: "ROSA",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "0",
      costo: "60",
      precioVenta: "350",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "C MARK",
      tipoEstructura: "CMJO-7008",
      color: "BLANCO",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "1",
      costo: "60",
      precioVenta: "350",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "HAGNUS",
      tipoEstructura: "250SP",
      color: "AZUL/BLCO",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "3",
      costo: "35",
      precioVenta: "300",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "HAGNUS",
      tipoEstructura: "251SP",
      color: "AZUL/BLCO/GRIS",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "4",
      costo: "35",
      precioVenta: "300",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "HAGNUS",
      tipoEstructura: "262SP",
      color: "NGO/GRIS7ROJ/AZ",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "4",
      costo: "35",
      precioVenta: "300",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "HAGNUS",
      tipoEstructura: "F8061",
      color: "CAFE",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "2",
      costo: "50",
      precioVenta: "300",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "HAGNUS",
      tipoEstructura: "227",
      color: "NARANJA/GRIS",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "1",
      costo: "40",
      precioVenta: "350",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "HAGNUS",
      tipoEstructura: "250SP",
      color: "AZUL",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "1",
      costo: "40",
      precioVenta: "350",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "COA",
      tipoEstructura: "MT-084",
      color: "NEGRO",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "1",
      costo: "90",
      precioVenta: "400",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "COA",
      tipoEstructura: "3027",
      color: "NEGRO",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "0",
      costo: "90",
      precioVenta: "400",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "SUSAN",
      tipoEstructura: "1011",
      color: "CAFE",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "1",
      costo: "32",
      precioVenta: "200",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "SUSAN",
      tipoEstructura: "1025",
      color: "NGRO/DOR/PLAT",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "3",
      costo: "32",
      precioVenta: "200",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "SUSAN",
      tipoEstructura: "ANA-1027",
      color: "NEGRO/AZUL",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "4",
      costo: "32",
      precioVenta: "350",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "ANIKI",
      tipoEstructura: "1051",
      color: "NEGRO",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "0",
      costo: "32",
      precioVenta: "350",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "OLIVE",
      tipoEstructura: "STP006SP",
      color: "clip/dor/negro",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "1",
      costo: "155",
      precioVenta: "500",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "OLIVE",
      tipoEstructura: "1006M",
      color: "AZUL",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "1",
      costo: "220",
      precioVenta: "600",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "OLIVE",
      tipoEstructura: "1502",
      color: "MORADO/ROJO",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "1",
      costo: "220",
      precioVenta: "600",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "OLIVE",
      tipoEstructura: "OX001",
      color: "NEGRO/AZUL",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "0",
      costo: "220",
      precioVenta: "600",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "OLIVE",
      tipoEstructura: "125",
      color: "VERDE",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "1",
      costo: "220",
      precioVenta: "600",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "GEMA",
      tipoEstructura: "164",
      color: "NEGRO",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "2",
      costo: "220",
      precioVenta: "600",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "GEMA",
      tipoEstructura: "155",
      color: "NEGRO",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "2",
      costo: "220",
      precioVenta: "600",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "BRIGHT VISION",
      tipoEstructura: "TR2269",
      color: "NEGRO",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "0",
      costo: "220",
      precioVenta: "600",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "GEMA",
      tipoEstructura: "3",
      color: "AZUL",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "1",
      costo: "200",
      precioVenta: "600",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "GEMA",
      tipoEstructura: "GEM-067",
      color: "AZUL",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "1",
      costo: "200",
      precioVenta: "600",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "GEMA",
      tipoEstructura: "GEM-004",
      color: "NEGRO/AZUL",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "4",
      costo: "200",
      precioVenta: "600",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "GEMA",
      tipoEstructura: "1085",
      color: "DORADO",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "0",
      costo: "200",
      precioVenta: "600",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "AXEL",
      tipoEstructura: "AXE 0787",
      color: "ROJO/NEGRO",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "1",
      costo: "55",
      precioVenta: "350",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "AXEL",
      tipoEstructura: "AXE 0875",
      color: "NEGRO/MORADO",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "2",
      costo: "55",
      precioVenta: "350",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "AXEL",
      tipoEstructura: "AXE0598",
      color: "CAFE",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "1",
      costo: "55",
      precioVenta: "350",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "FUNKY FRED",
      tipoEstructura: "6016",
      color: "GUINDA",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "0",
      costo: "160",
      precioVenta: "600",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "FUNKY FRED",
      tipoEstructura: "ODO 202K",
      color: "ROSA/MORADO",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "2",
      costo: "160",
      precioVenta: "600",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "FUNKY FRED",
      tipoEstructura: "006K",
      color: "ROSA/MOR.GUIN.",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "4",
      costo: "160",
      precioVenta: "600",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "FUNKY FRED",
      tipoEstructura: "107M",
      color: "NEGRO/AZUL",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "0",
      costo: "160",
      precioVenta: "600",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "LI DIKS",
      tipoEstructura: "LIK-10143",
      color: "ROJO",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "1",
      costo: "75",
      precioVenta: "500",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "LI KIDS",
      tipoEstructura: "LV-N020",
      color: "ROJO",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "1",
      costo: "75",
      precioVenta: "500",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "LI KIDS",
      tipoEstructura: "10145",
      color: "GRIS/ROJ./AZUL",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "6",
      costo: "75",
      precioVenta: "500",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "LI KIDS",
      tipoEstructura: "10142",
      color: "NEGRO/LILA/GRIS",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "3",
      costo: "75",
      precioVenta: "500",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "LI KIDS",
      tipoEstructura: "10147",
      color: "ROJO/NARANJA",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "2",
      costo: "75",
      precioVenta: "500",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "LI KIDS",
      tipoEstructura: "10138",
      color: "MELON/ROJO",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "2",
      costo: "75",
      precioVenta: "500",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "LI KIDS",
      tipoEstructura: "10140",
      color: "MELON",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "1",
      costo: "75",
      precioVenta: "500",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "TOP MODA",
      tipoEstructura: "TR01K",
      color: "N/AZ/ROSA",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "3",
      costo: "180",
      precioVenta: "600",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "GOOD KIDS",
      tipoEstructura: "5033",
      color: "NEGRO MATIZADO",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "0",
      costo: "90",
      precioVenta: "0",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "GOOD KIDS",
      tipoEstructura: "G5504",
      color: "NARANJA",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "2",
      costo: "50",
      precioVenta: "350",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "GOOD KIDS",
      tipoEstructura: "T1863",
      color: "NEGRO/ROJO",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "1",
      costo: "50",
      precioVenta: "350",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "LATIV",
      tipoEstructura: "LV-8094",
      color: "PLTA/DOR/NGRO/GRIS",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "6",
      costo: "32",
      precioVenta: "200",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "LATIV",
      tipoEstructura: "LV-N013",
      color: "CAFE",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "1",
      costo: "45",
      precioVenta: "350",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "LATIV",
      tipoEstructura: "LV-DM-006",
      color: "MOR/NEGRO",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "1",
      costo: "60",
      precioVenta: "300",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "LATIV",
      tipoEstructura: "LV-CPF-5012",
      color: "NEGR/CAFE",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "0",
      costo: "60",
      precioVenta: "300",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "LATIV",
      tipoEstructura: "LV-CPF-5015",
      color: "AZUL",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "0",
      costo: "60",
      precioVenta: "300",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "CNX-103K",
      tipoEstructura: "103K",
      color: "AZUL/NEGRO",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "1",
      costo: "80",
      precioVenta: "400",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "INUSUAL",
      tipoEstructura: "1016",
      color: "NEGRO",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "0",
      costo: "40",
      precioVenta: "350",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "KIOMY",
      tipoEstructura: "1015",
      color: "CAFE",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "0",
      costo: "48",
      precioVenta: "350",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "SONE",
      tipoEstructura: "2018",
      color: "CAFE",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "1",
      costo: "38",
      precioVenta: "350",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "CAFFEDY",
      tipoEstructura: "6685",
      color: "NEGRO/C",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "0",
      costo: "45",
      precioVenta: "350",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "HENDELLY",
      tipoEstructura: "HDL-22003",
      color: "CAF/NEGRO",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "0",
      costo: "45",
      precioVenta: "350",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "BEST",
      tipoEstructura: "18",
      color: "GUINDA/ROSA",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "0",
      costo: "35",
      precioVenta: "300",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "BEST",
      tipoEstructura: "29",
      color: "NEGRO",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "2",
      costo: "45",
      precioVenta: "300",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "BEST",
      tipoEstructura: "47R",
      color: "NGRO/GRIS",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "2",
      costo: "45",
      precioVenta: "300",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "S.T BAR",
      tipoEstructura: "STB-0767",
      color: "NEGRO",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "2",
      costo: "105",
      precioVenta: "500",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "PRINCE",
      tipoEstructura: "3P/100",
      color: "DORADO",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "1",
      costo: "120",
      precioVenta: "500",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "NATAHSA",
      tipoEstructura: "7017",
      color: "ROJO",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "1",
      costo: "48",
      precioVenta: "350",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "SOLAR",
      tipoEstructura: "CUADRADO -1",
      color: "AZUL",
      tipoMaterial: "SOLAR ECONOMICO",
      stock: "1",
      costo: "50",
      precioVenta: "200",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "SOLAR",
      tipoEstructura: "GOTA-2",
      color: "NEGRO",
      tipoMaterial: "SOLAR ECONOMICO",
      stock: "0",
      costo: "100",
      precioVenta: "200",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "SOLAR",
      tipoEstructura: "DEP-03",
      color: "NEGRO",
      tipoMaterial: "SOLAR ECONOMICO",
      stock: "1",
      costo: "95.5",
      precioVenta: "180",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "SOLAR",
      tipoEstructura: "DAM-004",
      color: "PLATA/NEGRO",
      tipoMaterial: "SOLAR ECONOMICO",
      stock: "0",
      costo: "110",
      precioVenta: "200",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "SOLAR",
      tipoEstructura: "ESP-005",
      color: "NEGRO/ROJO",
      tipoMaterial: "SOLAR ECONOMICO",
      stock: "0",
      costo: "49",
      precioVenta: "200",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "SOLAR",
      tipoEstructura: "JL-006",
      color: "NEGRO",
      tipoMaterial: "SOLAR ECONOMICO",
      stock: "1",
      costo: "83",
      precioVenta: "200",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "SOLAR",
      tipoEstructura: "LEN-007",
      color: "NEGRO",
      tipoMaterial: "SOLAR ECONOMICO",
      stock: "1",
      costo: "110",
      precioVenta: "200",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "SOLAR",
      tipoEstructura: "RED-008",
      color: "ESPEJEADO",
      tipoMaterial: "SOLAR ECONOMICO",
      stock: "1",
      costo: "165",
      precioVenta: "700",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "SOLAR",
      tipoEstructura: "DEPORT-009",
      color: "NEGRO/ROJO",
      tipoMaterial: "SOLAR ECONOMICO",
      stock: "0",
      costo: "57",
      precioVenta: "200",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "ARMAZON OFTALMICO",
      tipoEstructura: "SIN CODIGO",
      color: "NEGRO",
      tipoMaterial: "SOLAR ECONOMICO",
      stock: "0",
      costo: "0",
      precioVenta: "700",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "SOLAR",
      tipoEstructura: "GOT-010",
      color: "NEGRO",
      tipoMaterial: "SOLAR ECONOMICO",
      stock: "0",
      costo: "49",
      precioVenta: "200",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "ESTUCHE",
      tipoEstructura: "HILMOR",
      color: "ROSA",
      tipoMaterial: "ACCESORIO",
      stock: "1",
      costo: "0",
      precioVenta: "0",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "ESTUCHE",
      tipoEstructura: "HILMOR",
      color: "NEGRO",
      tipoMaterial: "ACCESORIO",
      stock: "0",
      costo: "0",
      precioVenta: "0",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "ESTUCHE",
      tipoEstructura: "HILMOR",
      color: "VERDE",
      tipoMaterial: "ACCESORIO",
      stock: "0",
      costo: "0",
      precioVenta: "0",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "ESTUCHES COL.",
      tipoEstructura: "",
      color: "",
      tipoMaterial: "ACCESORIO",
      stock: "0",
      costo: "20",
      precioVenta: "0",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "ESTUCHE",
      tipoEstructura: "NI�A",
      color: "ROJO",
      tipoMaterial: "ACCESORIO",
      stock: "1",
      costo: "0",
      precioVenta: "150",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "ESTUCHE",
      tipoEstructura: "NI�O",
      color: "AZUL",
      tipoMaterial: "ACCESORIO",
      stock: "3",
      costo: "0",
      precioVenta: "150",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "ESTUCHE",
      tipoEstructura: "DAMA",
      color: "NEGRO",
      tipoMaterial: "ACCESORIO",
      stock: "0",
      costo: "0",
      precioVenta: "150",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "FUNDAS",
      tipoEstructura: "UNISEX",
      color: "NEGRO",
      tipoMaterial: "ACCESORIO",
      stock: "0",
      costo: "10",
      precioVenta: "0",
      proveedor: "INDIGO",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "ESTUCHE",
      tipoEstructura: "CABALLERO",
      color: "NEGRO",
      tipoMaterial: "ACCESORIO",
      stock: "0",
      costo: "0",
      precioVenta: "150",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "ESTUCHE",
      tipoEstructura: "CABALLERO",
      color: "NEGRO MARCAS",
      tipoMaterial: "ACCESORIO",
      stock: "0",
      costo: "0",
      precioVenta: "0",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "ESTUCHE",
      tipoEstructura: "CABALLERO",
      color: "MARCAS",
      tipoMaterial: "ACCESORIO",
      stock: "0",
      costo: "0",
      precioVenta: "0",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "ESTUCHE",
      tipoEstructura: "SOLARES",
      color: "VARIOS",
      tipoMaterial: "ACCESORIO",
      stock: "0",
      costo: "0",
      precioVenta: "0",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "ESTUCHE",
      tipoEstructura: "DOLCE GABBANA",
      color: "NEGRO",
      tipoMaterial: "ACCESORIO",
      stock: "1",
      costo: "0",
      precioVenta: "0",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "ESTUCHE",
      tipoEstructura: "DOLCE GABBANA",
      color: "NEGRO",
      tipoMaterial: "ACCESORIO",
      stock: "1",
      costo: "0",
      precioVenta: "0",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "ESTUCHE",
      tipoEstructura: "CHANNEL",
      color: "NEGRO",
      tipoMaterial: "ACCESORIO",
      stock: "1",
      costo: "0",
      precioVenta: "0",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "ESTUCHE",
      tipoEstructura: "DIOR",
      color: "GRIS",
      tipoMaterial: "ACCESORIO",
      stock: "1",
      costo: "0",
      precioVenta: "0",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "ESTUCHE",
      tipoEstructura: "PRADA",
      color: "NEGRO",
      tipoMaterial: "ACCESORIO",
      stock: "2",
      costo: "0",
      precioVenta: "0",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "ESTUCHE",
      tipoEstructura: "PRADA",
      color: "MORADO/",
      tipoMaterial: "ACCESORIO",
      stock: "1",
      costo: "0",
      precioVenta: "0",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "ESTUCHE",
      tipoEstructura: "OPTICAS LUX",
      color: "AZUL",
      tipoMaterial: "ACCESORIO",
      stock: "1",
      costo: "0",
      precioVenta: "0",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "ESTUCHE",
      tipoEstructura: "LACOSTE",
      color: "VERDE",
      tipoMaterial: "ACCESORIO",
      stock: "2",
      costo: "0",
      precioVenta: "0",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "FRESHLOOK",
      tipoEstructura: "CONTACTO",
      color: "VERDE",
      tipoMaterial: "LENTE DE CONTACTO",
      stock: "1",
      costo: "0",
      precioVenta: "430",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "FRESHLOOK",
      tipoEstructura: "CONTACTO",
      color: "CAFE",
      tipoMaterial: "LENTE DE CONTACTO",
      stock: "1",
      costo: "0",
      precioVenta: "430",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "FRESHLOOK",
      tipoEstructura: "CONTACTO",
      color: "HONEY",
      tipoMaterial: "LENTE DE CONTACTO",
      stock: "1",
      costo: "0",
      precioVenta: "430",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "BAUSCH&LOMB",
      tipoEstructura: "-0.5",
      color: "GRADUACION",
      tipoMaterial: "LENTE DE CONTACTO",
      stock: "1",
      costo: "0",
      precioVenta: "450",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "BAUSCH&LOMB",
      tipoEstructura: "-1",
      color: "GRADUACION",
      tipoMaterial: "LENTE DE CONTACTO",
      stock: "1",
      costo: "0",
      precioVenta: "450",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "BAUSCH&LOMB",
      tipoEstructura: "-1.5",
      color: "GRADUACION",
      tipoMaterial: "LENTE DE CONTACTO",
      stock: "1",
      costo: "0",
      precioVenta: "450",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "BAUSCH&LOMB",
      tipoEstructura: "-2",
      color: "GRADUACION",
      tipoMaterial: "LENTE DE CONTACTO",
      stock: "1",
      costo: "0",
      precioVenta: "450",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "BAUSCH&LOMB",
      tipoEstructura: "-2.5",
      color: "GRADUACION",
      tipoMaterial: "LENTE DE CONTACTO",
      stock: "1",
      costo: "0",
      precioVenta: "450",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "BAUSCH&LOMB",
      tipoEstructura: "-3",
      color: "GRADUACION",
      tipoMaterial: "LENTE DE CONTACTO",
      stock: "1",
      costo: "0",
      precioVenta: "450",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "BAUSCH&LOMB",
      tipoEstructura: "-3.5",
      color: "GRADUACION",
      tipoMaterial: "LENTE DE CONTACTO",
      stock: "1",
      costo: "0",
      precioVenta: "450",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "BAUSCH&LOMB",
      tipoEstructura: "-4",
      color: "GRADUACION",
      tipoMaterial: "LENTE DE CONTACTO",
      stock: "1",
      costo: "0",
      precioVenta: "450",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "BAUSCH&LOMB",
      tipoEstructura: "-5",
      color: "GRADUACION",
      tipoMaterial: "LENTE DE CONTACTO",
      stock: "1",
      costo: "0",
      precioVenta: "450",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "BAUSCH&LOMB",
      tipoEstructura: "-6",
      color: "GRADUACION",
      tipoMaterial: "LENTE DE CONTACTO",
      stock: "1",
      costo: "0",
      precioVenta: "450",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "CORDON",
      tipoEstructura: "NI�O",
      color: "AZUL/CAFE",
      tipoMaterial: "ACCESORIO",
      stock: "4",
      costo: "18",
      precioVenta: "40",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "ESTUCHE",
      tipoEstructura: "DE CONTACTO",
      color: "BLANCO/GRIS",
      tipoMaterial: "ACCESORIO",
      stock: "1",
      costo: "55",
      precioVenta: "100",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "SOLUCION",
      tipoEstructura: "VISION",
      color: "60 ML",
      tipoMaterial: "ACCESORIO",
      stock: "1",
      costo: "35",
      precioVenta: "30",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "OPTI FREE",
      tipoEstructura: "LIQUIDO",
      color: "60ML",
      tipoMaterial: "ACCESORIO",
      stock: "6",
      costo: "0",
      precioVenta: "0",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "MICROFIBRA",
      tipoEstructura: "",
      color: "PA�O",
      tipoMaterial: "ACCESORIO",
      stock: "72",
      costo: "180",
      precioVenta: "30",
      proveedor: "FLOR",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "LACOSTE",
      tipoEstructura: "L1077",
      color: "NEGRO/CAFE",
      tipoMaterial: "LENTE SOLAR",
      stock: "6",
      costo: "0",
      precioVenta: "1799",
      proveedor: "ALIBABA",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "LOUIS VUITTON",
      tipoEstructura: "29635",
      color: "NEGRO/PLTA",
      tipoMaterial: "LENTE SOLAR",
      stock: "0",
      costo: "0",
      precioVenta: "12899",
      proveedor: "ALIBABA",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "LOUIS VUITTON",
      tipoEstructura: "29634",
      color: "NEGRO",
      tipoMaterial: "LENTE SOLAR",
      stock: "2",
      costo: "0",
      precioVenta: "14599",
      proveedor: "ALIBABA",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "LOUIS VUITTON",
      tipoEstructura: "G29634",
      color: "CAFE/DORADO",
      tipoMaterial: "LENTE SOLAR",
      stock: "1",
      costo: "0",
      precioVenta: "14599",
      proveedor: "ALIBABA",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "LOUIS VUITTON",
      tipoEstructura: "LV950",
      color: "NEGRO",
      tipoMaterial: "LENTE SOLAR",
      stock: "1",
      costo: "0",
      precioVenta: "10999",
      proveedor: "ALIBABA",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "LOUIS VUITTON",
      tipoEstructura: "LV950",
      color: "GRIS",
      tipoMaterial: "LENTE SOLAR",
      stock: "1",
      costo: "0",
      precioVenta: "10999",
      proveedor: "ALIBABA",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "HERMES",
      tipoEstructura: "2240",
      color: "NEGRO",
      tipoMaterial: "LENTE SOLAR",
      stock: "1",
      costo: "0",
      precioVenta: "2599",
      proveedor: "ALIBABA",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "ARMAZON PRADA",
      tipoEstructura: "56UV",
      color: "PLATEADO/NEGRO",
      tipoMaterial: "LENTE SOLAR",
      stock: "1",
      costo: "0",
      precioVenta: "3199",
      proveedor: "ALIBABA",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "ARMAZON PRADA",
      tipoEstructura: "5207",
      color: "NEGRO",
      tipoMaterial: "LENTE SOLAR",
      stock: "1",
      costo: "0",
      precioVenta: "3199",
      proveedor: "ALIBABA",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "PRADA",
      tipoEstructura: "PR4032",
      color: "DORADO",
      tipoMaterial: "LENTE SOLAR",
      stock: "1",
      costo: "0",
      precioVenta: "2550",
      proveedor: "ALIBABA",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "DIOR",
      tipoEstructura: "TR3220",
      color: "NEGRO/HUESO",
      tipoMaterial: "LENTE SOLAR",
      stock: "1",
      costo: "0",
      precioVenta: "200",
      proveedor: "ALIBABA",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "DIOR",
      tipoEstructura: "TR3220",
      color: "NEGRO",
      tipoMaterial: "LENTE SOLAR",
      stock: "0",
      costo: "0",
      precioVenta: "200",
      proveedor: "ALIBABA",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "RAY BAN",
      tipoEstructura: "RB3025",
      color: "VERDE/NEGRO",
      tipoMaterial: "LENTE SOLAR",
      stock: "1",
      costo: "0",
      precioVenta: "3999",
      proveedor: "ALIBABA",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "RAY BAN",
      tipoEstructura: "RB3025",
      color: "VERDE/DORADO",
      tipoMaterial: "LENTE SOLAR",
      stock: "2",
      costo: "0",
      precioVenta: "3999",
      proveedor: "ALIBABA",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "RAYBAN",
      tipoEstructura: "4165",
      color: "NEGRO",
      tipoMaterial: "LENTE SOLAR",
      stock: "2",
      costo: "0",
      precioVenta: "2199",
      proveedor: "ALIBABA",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "RAYBAN",
      tipoEstructura: "RB3584",
      color: "DORADO/MELON",
      tipoMaterial: "LENTE SOLAR",
      stock: "1",
      costo: "0",
      precioVenta: "3899",
      proveedor: "ALIBABA",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "RAYBAN",
      tipoEstructura: "RB3584-N",
      color: "NEGRO",
      tipoMaterial: "LENTE SOLAR",
      stock: "1",
      costo: "0",
      precioVenta: "3699",
      proveedor: "ALIBABA",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "RAYBAN",
      tipoEstructura: "RB3584",
      color: "NEGRO/DESVANECIDO",
      tipoMaterial: "LENTE SOLAR",
      stock: "1",
      costo: "0",
      precioVenta: "3699",
      proveedor: "ALIBABA",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "RAYBAN",
      tipoEstructura: "RB3584",
      color: "CAFE/NEGRO",
      tipoMaterial: "LENTE SOLAR",
      stock: "1",
      costo: "0",
      precioVenta: "3699",
      proveedor: "ALIBABA",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "RAYBAN",
      tipoEstructura: "RB3584",
      color: "DORADO/ROJO",
      tipoMaterial: "LENTE SOLAR",
      stock: "1",
      costo: "0",
      precioVenta: "3599",
      proveedor: "ALIBABA",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "RAYBAN",
      tipoEstructura: "RB3674",
      color: "ROJO/NE./DOR",
      tipoMaterial: "LENTE SOLAR",
      stock: "5",
      costo: "0",
      precioVenta: "4799",
      proveedor: "ALIBABA",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "RAYBAN",
      tipoEstructura: "RB3016",
      color: "NEGRO",
      tipoMaterial: "LENTE SOLAR",
      stock: "2",
      costo: "0",
      precioVenta: "2800",
      proveedor: "ALIBABA",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "CHANNEL",
      tipoEstructura: "6133",
      color: "NEGRO",
      tipoMaterial: "LENTE SOLAR",
      stock: "1",
      costo: "0",
      precioVenta: "2260",
      proveedor: "ALIBABA",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "CHANNEL",
      tipoEstructura: "3388",
      color: "NEGRO/DORADO",
      tipoMaterial: "LENTE SOLAR",
      stock: "1",
      costo: "0",
      precioVenta: "3500",
      proveedor: "ALIBABA",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "BURBERRY",
      tipoEstructura: "2273",
      color: "NEGRO",
      tipoMaterial: "LENTE SOLAR",
      stock: "1",
      costo: "0",
      precioVenta: "3779",
      proveedor: "ALIBABA",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "BURBERRY",
      tipoEstructura: "9026",
      color: "NEGRO/PIEL",
      tipoMaterial: "LENTE SOLAR",
      stock: "1",
      costo: "0",
      precioVenta: "1987",
      proveedor: "ALIBABA",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "GUCCI",
      tipoEstructura: "GG0142",
      color: "NEGRO/AR DORADO",
      tipoMaterial: "LENTE SOLAR",
      stock: "5",
      costo: "0",
      precioVenta: "7056",
      proveedor: "ALIBABA",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "GUCCI",
      tipoEstructura: "GG3535",
      color: "NEGRO",
      tipoMaterial: "LENTE SOLAR",
      stock: "1",
      costo: "0",
      precioVenta: "3799",
      proveedor: "ALIBABA",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "GUCCI",
      tipoEstructura: "1992",
      color: "TRANSPARENTE",
      tipoMaterial: "LENTE SOLAR",
      stock: "1",
      costo: "0",
      precioVenta: "3999",
      proveedor: "ALIBABA",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "GUCCI",
      tipoEstructura: "1992",
      color: "NEGRO",
      tipoMaterial: "LENTE SOLAR",
      stock: "0",
      costo: "0",
      precioVenta: "2999",
      proveedor: "ALIBABA",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "GUCCI",
      tipoEstructura: "GG0190",
      color: "DORADO/ROJO",
      tipoMaterial: "LENTE SOLAR",
      stock: "4",
      costo: "0",
      precioVenta: "2999",
      proveedor: "ALIBABA",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "GUCCI",
      tipoEstructura: "8518",
      color: "ROSA/NEGRO",
      tipoMaterial: "LENTE SOLAR",
      stock: "1",
      costo: "0",
      precioVenta: "2999",
      proveedor: "ALIBABA",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "GUCCI",
      tipoEstructura: "8518",
      color: "DORADO/NEGRO",
      tipoMaterial: "LENTE SOLAR",
      stock: "1",
      costo: "0",
      precioVenta: "2999",
      proveedor: "ALIBABA",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "GUCCI",
      tipoEstructura: "8518",
      color: "DORADO/CAFE",
      tipoMaterial: "LENTE SOLAR",
      stock: "1",
      costo: "0",
      precioVenta: "2999",
      proveedor: "ALIBABA",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "CARTIER",
      tipoEstructura: "10421",
      color: "DORADO/CAFE",
      tipoMaterial: "LENTE SOLAR",
      stock: "1",
      costo: "0",
      precioVenta: "3999",
      proveedor: "ALIBABA",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "CARTIER",
      tipoEstructura: "17331",
      color: "CEFE/DORADO",
      tipoMaterial: "LENTE SOLAR",
      stock: "1",
      costo: "0",
      precioVenta: "3999",
      proveedor: "ALIBABA",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "CARTIER",
      tipoEstructura: "17331",
      color: "MORADO/DORADO",
      tipoMaterial: "LENTE SOLAR",
      stock: "1",
      costo: "0",
      precioVenta: "3999",
      proveedor: "ALIBABA",
      categoria: "CABALLERO",
    },
    {
      opticaID: "6d7b9771-63f3-420e-8878-375ac1dd3bcc",
      nombreProducto: "BVLGARI",
      tipoEstructura: "9032",
      color: "NEGRO/DORADO",
      tipoMaterial: "ARMAZON OFTALMICO",
      stock: "1",
      costo: "0",
      precioVenta: "2361",
      proveedor: "ALIBABA",
      categoria: "CABALLERO",
    },
  ];
  const subirExcel = async () => {
    try {
      var count = 0;
      for (const pro of dataExcel) {
        count = count + 1;
        const newProducto = {
          opticaID: pro.opticaID,
          categoria: pro.categoria,
          nombreProducto: pro.nombreProducto,
          proveedor: pro.proveedor,
          costo: pro.costo,
          precioVenta: pro.precioVenta,
          color: pro.color,
          tipoEstructura: pro.tipoEstructura,
          urlImagen: pro.urlImagen,
          tipoMaterial: pro.tipoMaterial,
          stock: pro.stock.toString(),
        };
        const result = await API.graphql(
          graphqlOperation(createINVENTARIO, { input: newProducto })
        );
        console.log(result);
      }
      message.success(
        "Los productos se subieron correctamente correctamente total: " + count
      );
      cambiarComponent({ key: "11" });
    } catch (error) {
      console.log(error);
      message.error("Hubo un error contacta al administrador");
    }
  };

  const onFinish = async () => {
    try {
      const newProducto = {
        opticaID,
        categoria,
        nombreProducto,
        proveedor,
        costo,
        precioVenta,
        color,
        tipoEstructura,
        urlImagen,
        tipoMaterial,
        stock: stock.toString(),
      };
      const result = await API.graphql(
        graphqlOperation(createINVENTARIO, { input: newProducto })
      );
      console.log(result);
      message.success("El producto se ha creado correctamente");
      cambiarComponent({ key: "11" });
    } catch (error) {
      console.log(error);
      message.error("Hubo un error contacta al administrador");
    }
  };
  const handleImage = async (e) => {
    e.preventDefault();
    console.log(e);
    const file = e.target.files[0];
    if (!file) {
      console.log(undefined);
      // Manejar el caso en que no se haya seleccionado ningún archivo
      return;
    }
    const extension = file.name.split(".")[1];
    const name = file.name.split(".")[0];
    const keys = `images/${uuidv4()}${name}.${extension}`;
    const urls = `https://${bucket}.s3.${region}.amazonaws.com/public/${keys}`;
    console.log(keys, file, file.type);
    console.log(urls);

    try {
      const image1 = await Storage.put(keys, file, {
        level: "public",
        contentType: file.type,
      });
      console.log(image1);
      // const image1 = await Storage.get(keys, { level: "public" });
      setUrlImagen(urls);
      console.log("archivo guardado");
      message.success("Imagen cargada exitósamente");
    } catch (error) {
      console.log(error);
      message.error("No se subió correctamente, contacta al administrador");
    }
  };
  return (
    <div>
      <h1>CREAR PRODUCTO</h1>
      <Form layout="vertical" name="crearLente" onFinish={onFinish}>
        <div
          style={{
            display: "grid",
            gap: "8px",
            gridTemplateColumns: "repeat(4, 1fr)",
          }}
        >
          <Form.Item
            label="Nombre Producto"
            name="nombreProducto"
            rules={[{ required: true, message: "Este campo es requerido" }]}
          >
            <Input
              value={nombreProducto}
              placeholder="Ingresa el nombre del producto"
              onChange={(e) => setNombreProducto(e.target.value)}
            />
          </Form.Item>
          <Form.Item
            label="Categoria"
            rules={[{ required: true, message: "Este campo es requerido" }]}
          >
            <Select
              //   defaultValue={categoria}
              onSelect={(e) => setCategoria(e)}
              placeholder="Select una Categoria"
            >
              <Option value="DAMA">DAMA</Option>
              <Option value="CABALLERO">CABALLERO</Option>
              <Option value="BOY">BOY</Option>
            </Select>
          </Form.Item>
          {opticas.length > 0 && (
            <LaboratorioSelector
              groupName={groupName}
              setOpticaID={setOpticaID}
              opticas={opticas}
            />
          )}
          <Form.Item
            label="Proveedor"
            rules={[{ required: true, message: "Este campo es requerido" }]}
          >
            <Input
              placeholder="Ingrese el nombre del proveedor"
              value={proveedor}
              onChange={(e) => setProveedor(e.target.value)}
            />
          </Form.Item>

          <Form.Item
            label="Costo"
            name="costo"
            rules={[{ required: true, message: "Este campo es requerido" }]}
          >
            <Input
              placeholder="Ingresa el costo del producto"
              value={costo}
              onChange={(e) => {
                if (e.target.value === "") {
                  setCosto(0);
                } else {
                  setCosto(Number(e.target.value));
                }
              }}
            />
          </Form.Item>
          <Form.Item
            label="Precio de Venta"
            name="precioVenta"
            rules={[{ required: true, message: "Este campo es requerido" }]}
          >
            <Input
              placeholder="Ingresa el precio de venta"
              value={precioVenta}
              onChange={(e) => {
                if (e.target.value === "") {
                  setPrecioVenta(0);
                } else {
                  setPrecioVenta(Number(e.target.value));
                }
              }}
              style={{ width: "100%" }}
            />
          </Form.Item>
          <Form.Item
            label="Stock"
            name="stock"
            rules={[{ required: true, message: "Este campo es requerido" }]}
          >
            <Input
              placeholder="Ingresa la cantidad a agregar"
              value={stock}
              onChange={(e) => {
                if (e.target.value === "") {
                  setStock(0);
                } else {
                  setStock(Number(e.target.value));
                }
              }}
              style={{ width: "100%" }}
            />
          </Form.Item>
          <Form.Item
            label="Color"
            name="color"
            // rules={[{ required: true, message: "Este campo es requerido" }]}
          >
            <Input
              placeholder="Ingresa el color del producto"
              value={color}
              onChange={(e) => setColor(e.target.value)}
            />
          </Form.Item>
          <Form.Item
            label="Cod Armazon"
            name="tipoEstructura"
            // rules={[{ required: true, message: "Este campo es requerido" }]}
          >
            <Input
              placeholder="Ingresa el tipo de estructura"
              value={tipoEstructura}
              onChange={(e) => setTipoEstructura(e.target.value)}
            />
          </Form.Item>
          <Form.Item
            label="Imagen"
            name="urlImagen"
            // rules={[{ required: true, message: "Este campo es requerido" }]}
          >
            <Input type="file" accept="jpg" onChange={(e) => handleImage(e)} />
            {/* <Upload
              // customRequest={(info) => handleImage(info)}
              onChange={(e) => handleImage(e)}
              action="http://localhost:3000/superadmin"
              name="lente"
              accept=".apng,.avif,.gif,.jpg,.jpeg,.jfif,.pjpeg,.pjp,.png,.svg,.webp"
              listType="picture"
            >
              <Button icon={<UploadOutlined />}>Click to upload</Button>
            </Upload> */}
          </Form.Item>
          <Form.Item
            label="Tipo Material"
            name="tipoMaterial"
            // rules={[{ required: true, message: "Este campo es requerido" }]}
          >
            <Input
              placeholder="Ingresa el tipo de material"
              value={tipoMaterial}
              onChange={(e) => setTipoMaterial(e.target.value)}
            />
          </Form.Item>
        </div>
        <div style={{ marginTop: 10 }}>
          <Button title="Save" htmlType="submit" type="primary">
            Guardar
          </Button>
        </div>
      </Form>
      <div style={{ marginTop: 10 }}>
        <Button title="Save" onClick={() => subirExcel()} type="primary">
          Subir excel
        </Button>
      </div>
    </div>
  );
}

export default CrearInventario;
